#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi 

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# preferences
xset r rate 180 80
xset m 1 4

# start composite manager
xcompmgr &

# set background image
~/.fehbg &

# hide cursor while typing
# rxbanish &

# notification daemon
{ sleep 2; runst; } &

# start i3-workspace-groups
#exec i3-workspace-groups server &

# start polkit auth agent
lxpolkit &

# start i3
exec i3
