#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
xsetroot -cursor_name left_ptr &

bspc config border_width          1
bspc config window_gap            4
bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config normal_border_color   "#101010"
bspc config focused_border_color  "#474747"
