#!/usr/bin/env bash

alias v='vim'
alias g='git'
alias c='xclip -selection clipboard'
alias p='xclip -o'
alias x='startx'
alias ls='exa --icons --color-scale'
alias ll='ls -lah'
alias bat='bat --theme "TwoDark"'
alias b='bat'
alias cg='cargo'
alias rustc++='rustup update'
alias cgr='cgrun debug'
alias cgrr='cgrun release'
alias ktop='bpytop'
alias code='vscodium'
alias bt='bluetoothctl'
alias cap='menyoki -q cap --root --size $(slop -k) png save - | rpaste - 2>/dev/null | c ; notify'
alias rec='menyoki -q rec --root --size $(slop -k) gif --gifski save - | rpaste - 2>/dev/null | c ; notify'
alias ezrec='menyoki rec -r --select gif --gifski -q 75 save -d'
alias mictest='arecord -vvv -f dat /dev/null'
alias pacman='sudo pacman'
alias pac='pacman'
alias paclogi='paclog --grep="installed|upgraded"'
alias upd='paru -Syuv'
alias sys='systemctl'
alias src="source $HOME/.bashrc"
alias wee="weechat"

alias rm='trash'
alias mdp='mdp -sc'
alias tasks='taskwarrior-tui'
alias lswin='xwininfo -tree -root'
alias rebuildpy='pacman -Qoq /usr/lib/python3.8/ | paru -S --rebuild -'
alias mc="java -jar $HOME/.minecraft/TLauncher-2.79.jar"
alias dsf='diff-so-fancy'
alias bino='WGPU_BACKEND=gl binocle'
alias chksrv='chkservice'
alias cdj='cd "$(xplr --print-pwd-as-result)"'

